# -*- coding: utf-8 -*-
"""Airline_Customer_Satisfaction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sHle1Anrs4pmbx4DmnoeOQMS-LsniV4m

# **✈️ Airline Customer Satisfaction**

From various factor of a airline services will contribute to customer **satisfaction** or lead to **dissatisfaction**.

From the Customer Satisfaction survey dataset:

● We will **Identify specific element** of airline services that significantly contribute to positive customer experiences. This understanding will enable **targeted service adjustments** to elevate overall satisfaction.

● Uncovering Pain Points: Conversely, we will **pinpoint the factors** that lead to customer **dissatisfaction**. **Addressing** these "bad factors" is crucial for minimizing negative experiences.

● Visualizing Relationships: Through the composition plots and other insightful visualizations, we will explore the relationships between various service variables and confidenly recommendations and suggestions for airline.

## **1. Data source**

Source: Public dataset from Kaggle

(Airline Customer Satisfaction: https://www.kaggle.com/datasets/raminhuseyn/airline-customer-satisfaction)

### Import needed libraries
"""

# Import needed libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm
import kagglehub

"""### Load the data"""

# Download latest version
path = kagglehub.dataset_download("raminhuseyn/airline-customer-satisfaction")

# Load the data from uploaded csv file
df = pd.read_csv(path + "/Airline_customer_satisfaction.csv")
df = df.dropna()

"""### Look at data
Let's take a look at the last 5 rows to be sure, that data is loaded properly.
"""

df.head(5)

"""### Look at columns, dtypes and non-null values."""

df.info()

objectColumns = df.select_dtypes(include='object').columns
objectColumns

"""### Let make columns as object to string."""

# df = df.convert_dtypes()
df.info()

"""### Basic descriptive statistics"""

df.describe()

"""## **2. Exploratory the Data**

### Satisfied and Dissatisfied
"""

plt.title("Satisfied vs Dissatisfied", fontsize = 12, weight='bold')
plt.pie(df['satisfaction'].value_counts(),
        labels=df['satisfaction'].value_counts().index,
        radius=1,
        autopct='%.2f%%',
        textprops={'fontsize': 10, 'fontweight': 'bold'},
        colors = sns.color_palette('Spectral'))
plt.show()

"""● The number of **Satisfied** customers **Exceeds** the number of **Dissatisfied** customers, indicating a prevailing trend towards positive experiences with the flight service.

### Business Travel vs Personal Travel
"""

plt.title("Business Travel vs Personal Travel", fontsize = 12, weight='bold')
plt.pie(df['Type of Travel'].value_counts(),
        labels=df['Type of Travel'].value_counts().index,
        radius=1,
        autopct='%.2f%%',
        textprops={'fontsize': 10, 'fontweight': 'bold'},
        colors = sns.color_palette('pastel'))
plt.show()

"""**・Business** travel accounts for the vast majority, at 69.08%. This significant share suggests that for the population or dataset this chart represents, travel is predominantly undertaken for professional purposes.

・Substantial, but Lesser, Personal Travel: Personal travel, while a considerable segment, makes up 30.92%. This indicates that personal trips, vacations, and leisure travel, though present, are less frequent or less impactful in volume than business-related travel.

### Loyal Customer vs Disloyal Customer
"""

plt.title("Loyal Customer vs Disloyal Customer", fontsize = 12, weight='bold')
plt.pie(df['Customer Type'].value_counts(),
        labels=["Loyal Customer", "Disloyal Customer"],
        radius=1,
        autopct='%.2f%%',
        textprops={'fontsize': 10, 'fontweight': 'bold'},
        colors = sns.color_palette('husl'))
plt.show()

"""● Overwhelming Customer Loyalty: The most striking observation is the significant proportion of Loyal Customers, accounting for 81.69%.

## **3. Look at Satisfied Customers**
"""

obj_columns = df.select_dtypes(include='object').columns

# Convert categorical variable into indicator value
encoded_data = pd.get_dummies(df, columns = obj_columns)

x = encoded_data.drop(['satisfaction_satisfied', 'satisfaction_dissatisfied'], axis=1).astype('float64')
satisfied_y = encoded_data['satisfaction_satisfied']

x = sm.add_constant(x)
satisfied_model = sm.Logit(satisfied_y, x).fit()

# look at model summary
print(satisfied_model.summary())

"""・Let look at **positive coefficient** (coef) the independent variable increases, it is being satisfied increase (i.e., higher probability of satisfaction).

List of positive coefficient: Seat comfort, Gate location, Inflight entertainment, Online support, Ease of Online booking, On-board service, Leg room service, Baggage handling, Checkin service, Cleanliness, Online boarding, Departure Delay in Minutes.

・Focus on 3 most of positive coefficient element will be make satisfied increase.

**Inflight entertainment** (**0.7195**): This has the largest positive coefficient, indicating a strong positive association with customer satisfaction.

**On-board service** (**0.3131**): Significant positive impact.

**Seat comfort** (**0.2863**): Significant positive impact.

### **Satisfied customers inflight entertainment ratings**
"""

# Retrieve Satisfied Customer
satisfied_df = df[df["satisfaction"] == "satisfied"]

plt.figure(figsize=[15, 5])
plt.hist(satisfied_df["Inflight entertainment"], bins=15, color="#191970")
plt.xlabel("Inflight entertainment Rate");
plt.ylabel("Frequency");
plt.title("Satisfied customers inflight entertainment ratings")
plt.grid(True)
plt.show()

"""### **Satisfied customers on-board service ratings**"""

# On-board service ratings Satisfied customers
plt.figure(figsize=[15, 5])
plt.hist(satisfied_df["On-board service"], bins=15, color="#4169E1")
plt.xlabel("On-board service Rate")
plt.ylabel("Frequency")
plt.title("Satisfied customers on-board service ratings")
plt.grid(True)
plt.show()

"""### **Satisfied customers seat comfort ratings**"""

# On-board service ratings Satisfied customers
plt.figure(figsize=[15, 5])
plt.hist(satisfied_df["Seat comfort"], bins=15, color="#00BFFF")
plt.xlabel("Seat comfort Rate")
plt.ylabel("Frequency")
plt.title("Satisfied customers seat comfort ratings")
plt.grid(True)
plt.show()

"""## **4. Look at Dissatisfied Customers**"""

obj_columns = df.select_dtypes(include='object').columns
º
# Convert categorical variable into indicator value
encoded_data = pd.get_dummies(df, columns = obj_columns)

x = encoded_data.drop(['satisfaction_satisfied', 'satisfaction_dissatisfied'], axis=1).astype('float64')
dissatisfied_y = encoded_data['satisfaction_dissatisfied']

x = sm.add_constant(x)
dissatisfied_model = sm.Logit(dissatisfied_y, x).fit()

# look at model summary
print(dissatisfied_model.summary())

"""・Let look at **positive coefficient** (coef) the independent variable increases, it is being dissatisfied increase (i.e., higher probability of satisfaction).
List of positive coefficient: Departure/Arrival time convenient, Food and drink, Inflight wifi service, Arrival Delay in Minutes.

・Focus on 3 most of positive coefficient element will be make dissatisfied increase.

**Departure/Arrival time convenient** (**0.2201**): This is the most impactful service-related factor directly contributing to dissatisfaction among the reliable coefficients. A less convenient departure/arrival time significantly increases the likelihood of dissatisfaction.

**Food and Drink** (**0.2084**): Poor ratings for food and drink also have a substantial negative impact on satisfaction.

**Inflight wifi service** (**0.0914**): Lower quality of inflight Wi-Fi service also contributes to dissatisfaction.

### **Dissatisfied customers Departure/Arrival time convenient ratings**
"""

# Retrieve Dissatisfied Customer
dissatisfied_df = df[(df["satisfaction"] == "dissatisfied") & (df["Type of Travel"] == "Business travel")]
# dissatisfied_df = df[(df["satisfaction"] == "dissatisfied") & (df["Customer Type"] == "Loyal Customer")]
# dissatisfied_df = df[(df["satisfaction"] == "dissatisfied") & (df["Customer Type"] == "disloyal Customer")]

# Dissatisfied customers Departure/Arrival time convenient ratings
plt.figure(figsize=[15, 5])
plt.hist(dissatisfied_df["Departure/Arrival time convenient"], bins=15, color="#4B352A")
plt.xlabel("Departure/Arrival time convenient Rate")
plt.ylabel("Frequency")
plt.title("Dissatisfied customers Departure/Arrival time convenient ratings")
plt.grid(True)
plt.show()

"""### **Dissatisfied customers Food and Drink ratings**"""

# Dissatisfied customers Food and drink ratings
plt.figure(figsize=[15, 5])
plt.hist(dissatisfied_df["Food and drink"], bins=15, color="#CA7842")
plt.xlabel("Food and drink Rate")
plt.ylabel("Frequency")
plt.title("Dissatisfied customers Food and drink ratings")
plt.grid(True)

"""### **Dissatisfied customers Inflight wifi service ratings**"""

dissatisfied_df = df[(df["satisfaction"] == "dissatisfied") & (df["Type of Travel"] == "Business travel")]
# dissatisfied_df = df[(df["satisfaction"] == "dissatisfied") & (df["Type of Travel"] == "Personal Travel")]

# Dissatisfied customers Inflight wifi service ratings
plt.figure(figsize=[15, 5])
plt.hist(dissatisfied_df["Inflight wifi service"], bins=15, color="#E8C999")
plt.xlabel("Inflight wifi service Rate")
plt.ylabel("Frequency")
plt.title("Dissatisfied customers Inflight wifi service ratings")
plt.grid(True)
plt.show()